import random

# mood_suggestions = {
#     "😊 Happy": [
#         ("'Happy' - Pharrell Williams", "Smile big, you deserve it!"),
#         ("'Good Vibrations' - Beach Boys", "Keep shining, you’re doing great!"),
#     ],
#     "😢 Sad": [
#         ("'Fix You' - Coldplay", "Tough times don’t last. You do."),
#         ("'Someone Like You' - Adele", "Let it out and let it go."),
#     ],
#     "😠 Angry": [
#         ("'Smells Like Teen Spirit' - Nirvana", "Breathe. You are in control."),
#         ("'Breaking the Habit' - Linkin Park", "Let the music help you cool down."),
#     ],
#     "😌 Calm": [
#         ("'Weightless' - Marconi Union", "Peace begins with a deep breath."),
#         ("'River Flows In You' - Yiruma", "Stillness speaks volumes."),
#     ],
#     "😰 Stressed": [
#         ("'Let It Be' - The Beatles", "You are doing your best."),
#         ("'Breathe Me' - Sia", "Pause. Reset. Restart."),
#     ],
#     "🤩 Excited": [
#         ("'Uptown Funk' - Bruno Mars", "Ride that high!"),
#         ("'On Top of the World' - Imagine Dragons", "Energy like yours is contagious!"),
#     ],
# }
mood_suggestions = {
    "😊 Happy": [
        ("'Best Day of My Life' - American Authors", "Celebrate every little win."),
        ("'Walking on Sunshine' - Katrina & The Waves", "Let your light shine bright."),
        ("'Can't Stop the Feeling!' - Justin Timberlake", "Good vibes only."),
        ("'Sugar' - Maroon 5", "Sweet moments make life great."),
        ("'I Gotta Feeling' - Black Eyed Peas", "Tonight’s gonna be a good night!"),
        ("'Good Life' - OneRepublic", "You’re living the dream."),
        ("'Valerie' - Mark Ronson ft. Amy Winehouse", "You're radiating joy."),
        ("'Send Me on My Way' - Rusted Root", "You’re headed toward happiness."),
        ("'I'm Yours' - Jason Mraz", "Be yourself — it’s beautiful."),
        ("'Put Your Records On' - Corinne Bailey Rae", "Relax and let your soul sing."),
        ("'Lush Life' - Zara Larsson", "Enjoy every second of life."),
        ("'On Top of the World' - Imagine Dragons", "You deserve this feeling."),
        ("'Geronimo' - Sheppard", "Leap into life with joy!"),
        ("'Shake It Off' - Taylor Swift", "Keep dancing through life."),
        ("'Shut Up and Dance' - WALK THE MOON", "Let loose and enjoy!"),
        ("'Dynamite' - BTS", "Shine through like the stars."),
        ("'Good as Hell' - Lizzo", "Feel yourself. You’re amazing."),
        ("'Mr. Blue Sky' - Electric Light Orchestra", "Everything is bright and clear."),
        ("'Firework' - Katy Perry", "Let your colors burst!"),
        ("'Juice' - Lizzo", "You’re 100% that star."),
        ("'Beautiful Day' - U2", "Enjoy every heartbeat."),
        ("'Uptown Girl' - Billy Joel", "Smile wide, life is sweet."),
        ("'This Is Me' - Keala Settle", "Be bold, be proud."),
        ("'Hey Ya!' - Outkast", "Dance like no one's watching."),
        ("'Treasure' - Bruno Mars", "You’re golden."),
        ("'Me Too' - Meghan Trainor", "Confidence looks good on you."),
        ("'Pocketful of Sunshine' - Natasha Bedingfield", "Keep shining."),
        ("'Happy Together' - The Turtles", "Togetherness fuels happiness."),
        ("'So Good' - B.o.B ft. Ryan Tedder", "Everything’s working out."),
        ("'Love Myself' - Hailee Steinfeld", "Self-love looks great on you."),
    ],

    "😢 Sad": [
        ("'All I Want' - Kodaline", "It's okay to feel. Healing begins here."),
        ("'Jealous' - Labrinth", "Let the tears cleanse the soul."),
        ("'The Night We Met' - Lord Huron", "It's okay to miss someone."),
        ("'Skinny Love' - Bon Iver", "Whispers heal silent pain."),
        ("'I Will Always Love You' - Whitney Houston", "Some love stays forever."),
        ("'Let Her Go' - Passenger", "Sometimes letting go is loving too."),
        ("'Say Something' - A Great Big World", "You are not alone."),
        ("'Youth' - Daughter", "Sadness doesn’t define your whole story."),
        ("'The Scientist' - Coldplay", "Even pain has purpose."),
        ("'Creep' - Radiohead", "You're still worthy."),
        ("'Tears Dry On Their Own' - Amy Winehouse", "You are strong."),
        ("'Hurt' - Christina Aguilera", "It's okay to grieve."),
        ("'Someone Like You' - Adele", "You’ll love again."),
        ("'Lonely' - Akon", "You are never truly alone."),
        ("'I Miss You' - Blink-182", "Memories can be soft shoulders."),
        ("'Let It Go' - James Bay", "It’s okay to release the weight."),
        ("'Jar of Hearts' - Christina Perri", "Protect your heart."),
        ("'Supermarket Flowers' - Ed Sheeran", "Some losses live with grace."),
        ("'Say You Love Me' - Jessie Ware", "Let it all out."),
        ("'Fix You' - Coldplay", "Someone will hold your pieces."),
        ("'She Used to Be Mine' - Sara Bareilles", "Remember, you’re still here."),
        ("'Un-break My Heart' - Toni Braxton", "The pain won’t last forever."),
        ("'Dancing On My Own' - Robyn", "You’re allowed to be soft."),
        ("'The A Team' - Ed Sheeran", "Gentle hearts shine differently."),
        ("'Youth' - Troye Sivan", "Sadness can’t steal your spark."),
        ("'I’ll Be There' - Jess Glynne", "You’ve got support."),
        ("'Back to December' - Taylor Swift", "Reflect, but don’t dwell."),
        ("'Let Me Down Slowly' - Alec Benjamin", "Fall, but rise stronger."),
        ("'Forever Young' - Alphaville", "Tears don’t age your spirit."),
        ("'When I Was Your Man' - Bruno Mars", "Lessons in every loss."),
    ],

    "😠 Angry": [
        ("'Breaking the Habit' - Linkin Park", "Let the rage flow out."),
        ("'Numb' - Linkin Park", "Scream it out. Then let go."),
        ("'You Oughta Know' - Alanis Morissette", "Feel it. Own it."),
        ("'Lose Yourself' - Eminem", "Turn fury into focus."),
        ("'Before He Cheats' - Carrie Underwood", "Take your power back."),
        ("'Killing In The Name' - Rage Against the Machine", "Channel the fire."),
        ("'Fighter' - Christina Aguilera", "You are stronger now."),
        ("'Misery Business' - Paramore", "Release the pressure."),
        ("'Gives You Hell' - The All-American Rejects", "Win silently."),
        ("'Radioactive' - Imagine Dragons", "Turn fire into fuel."),
        ("'Savage' - Megan Thee Stallion", "Keep your crown."),
        ("'In The End' - Linkin Park", "Let it all fall away."),
        ("'Stronger' - Kanye West", "What doesn’t kill you..."),
        ("'Raise Your Glass' - P!nk", "Rebel with grace."),
        ("'Warriors' - Imagine Dragons", "You’re built for battles."),
        ("'Uprising' - Muse", "You rise. Always."),
        ("'I Hate Everything About You' - Three Days Grace", "Vent it out."),
        ("'Chop Suey!' - System of a Down", "Let it explode — then breathe."),
        ("'The Way I Am' - Eminem", "Own your chaos."),
        ("'Just Like a Pill' - P!nk", "Your sanity matters."),
        ("'Headstrong' - Trapt", "Unapologetically fierce."),
        ("'Bodies' - Drowning Pool", "Let the noise release the pain."),
        ("'My Songs Know What You Did' - Fall Out Boy", "Turn rage into rhythm."),
        ("'Bad Guy' - Billie Eilish", "Reclaim the narrative."),
        ("'No Tears Left To Cry' - Ariana Grande", "Up from the ashes."),
        ("'You Should See Me in a Crown' - Billie Eilish", "Anger turns to power."),
        ("'Unstoppable' - Sia", "Nothing can break you."),
        ("'Monster' - Skillet", "Tame the beast."),
        ("'Control' - Halsey", "Find strength in storms."),
        ("'Believer' - Imagine Dragons", "Pain built the masterpiece."),
    ],

    "😌 Calm": [
        ("'Weightless' - Marconi Union", "Stillness speaks volumes."),
        ("'Sunset Lover' - Petit Biscuit", "Let the waves carry your mind."),
        ("'River Flows In You' - Yiruma", "Let the stillness comfort you."),
        ("'Bloom' - The Paper Kites", "Let peace grow inside."),
        ("'Opus 55' - Dustin O’Halloran", "Let the notes relax your breath."),
        ("'Experience' - Ludovico Einaudi", "Surrender to stillness."),
        ("'Night Owl' - Galimatias", "Float above your stress."),
        ("'Holocene' - Bon Iver", "You are right where you need to be."),
        ("'Ocean Eyes' - Billie Eilish", "Breathe into the calm."),
        ("'Intro' - The xx", "Drift into serenity."),
        ("'Reverie' - Claude Debussy", "Let your mind wander freely."),
        ("'Spiegel im Spiegel' - Arvo Pärt", "Let your thoughts echo gently."),
        ("'Weightless Pt 2' - Marconi Union", "Light as air."),
        ("'Soft Winds' - Chillhop Essentials", "Ease into this moment."),
        ("'Nocturne in E-flat Major' - Chopin", "Rest with elegance."),
        ("'Lavender Haze' - Taylor Swift", "Float in stillness."),
        ("'Calm Down' - Rema ft. Selena Gomez", "Relax and flow."),
        ("'Angel' - Sarah McLachlan", "Breathe easy."),
        ("'Clair de Lune' - Debussy", "Peace in every note."),
        ("'Green Eyes' - Coldplay", "Serenity in sound."),
        ("'To Build A Home' - The Cinematic Orchestra", "You are safe."),
        ("'Fix You (Instrumental)' - Coldplay", "Gentle healing."),
        ("'Motion Picture Soundtrack' - Radiohead", "A lullaby for the mind."),
        ("'Slow Dancing in the Dark' - Joji", "Embrace the quiet."),
        ("'High Hopes (Instrumental)' - Pink Floyd", "Dream freely."),
        ("'Saturn' - Sleeping At Last", "Universal peace."),
        ("'Rain Sounds' - Nature Sounds", "Nature knows peace."),
        ("'Pure Shores' - All Saints", "Float to calm shores."),
        ("'Lofi Rain' - Chillhop Music", "Steady, rhythmic peace."),
        ("'Cicada' - Andrew Belle", "Drift with the moment."),
    ],

    "😰 Stressed": [
        ("'Let It Be' - The Beatles", "Let go, flow forward."),
        ("'Breathe Me' - Sia", "One breath at a time."),
        ("'Come Away With Me' - Norah Jones", "Leave the chaos behind."),
        ("'Halo' - Beyoncé", "Light breaks the stress."),
        ("'Somewhere Only We Know' - Keane", "Retreat to peace."),
        ("'A Thousand Years' - Christina Perri", "Slow time down."),
        ("'Demons' - Imagine Dragons", "Face them, you’re stronger."),
        ("'Fix You' - Coldplay", "Mend gently."),
        ("'Let Go' - Frou Frou", "You can release control."),
        ("'Human' - Christina Perri", "It’s okay not to be okay."),
        ("'All of Me' - John Legend", "Love can calm the storm."),
        ("'Say You Won’t Let Go' - James Arthur", "Hold onto support."),
        ("'Cold' - Chris Stapleton", "Feel it, then release."),
        ("'Love on the Brain' - Rihanna", "Soften the load."),
        ("'Satellite' - Harry Styles", "Spin into calm."),
        ("'Hold On' - Chord Overstreet", "This too shall pass."),
        ("'Falling Slowly' - Glen Hansard", "Move at your pace."),
        ("'The Light' - Disturbed", "A flame even in the dark."),
        ("'Yellow' - Coldplay", "Even stars feel pressure."),
        ("'Just Give Me a Reason' - Pink", "Pause to process."),
        ("'Let Me Love You' - Mario", "You're not alone."),
        ("'Breathe' - Pink Floyd", "Just breathe."),
        ("'Afterglow' - Ed Sheeran", "Peace follows effort."),
        ("'Ribs' - Lorde", "Nostalgia relieves."),
        ("'Somebody Else' - The 1975", "It’s okay to reset."),
        ("'Gravity' - Sara Bareilles", "Let yourself land."),
        ("'Slow Down' - Nichole Nordeman", "Ease into life."),
        ("'In My Veins' - Andrew Belle", "It’ll pass."),
        ("'Stay' - Rihanna", "Sometimes stillness is key."),
        ("'The Archer' - Taylor Swift", "Be gentle with yourself."),
    ],

    "🤩 Excited": [
        ("'On Top of the World' - Imagine Dragons", "Energy like yours is contagious!"),
        ("'Shut Up and Dance' - Walk The Moon", "Don’t hold back the joy!"),
        ("'Can't Hold Us' - Macklemore & Ryan Lewis", "Unstoppable energy."),
        ("'Levitating' - Dua Lipa", "You’re flying high!"),
        ("'High Hopes' - Panic! At The Disco", "Your dreams are valid."),
        ("'Good Time' - Owl City & Carly Rae Jepsen", "Let the good times roll."),
        ("'Electric Love' - BORNS", "Buzzing with passion."),
        ("'Born This Way' - Lady Gaga", "Express your excitement."),
        ("'Tik Tok' - Ke$ha", "Live in the now."),
        ("'Let's Go' - Calvin Harris", "No limits today."),
        ("'Wake Me Up' - Avicii", "Live, love, dance."),
        ("'Run the World' - Beyoncé", "You’re in control."),
        ("'Blinding Lights' - The Weeknd", "Shine your brightest."),
        ("'Cake by the Ocean' - DNCE", "Savor the chaos."),
        ("'Sucker' - Jonas Brothers", "Admit it — you’re glowing!"),
        ("'Talk Dirty' - Jason Derulo", "Fun is your fuel."),
        ("'She’s So High' - Tal Bachman", "Confidence rising."),
        ("'Don’t Start Now' - Dua Lipa", "You’re thriving."),
        ("'I Like Me Better' - Lauv", "Love your vibe."),
        ("'Classic' - MKTO", "You’re timeless."),
        ("'Feel It Still' - Portugal. The Man", "Keep that rhythm."),
        ("'Boom Clap' - Charli XCX", "Your joy is explosive."),
        ("'Dance Monkey' - Tones and I", "Keep the moves going."),
        ("'This Girl' - Kungs vs. Cookin’", "Electrifying energy."),
        ("'No Brainer' - DJ Khaled", "You’re on fire!"),
        ("'Light It Up' - Major Lazer", "Glow all out."),
        ("'Super Bass' - Nicki Minaj", "Vibes = 100%."),
        ("'Bang Bang' - Jessie J, Ariana, Nicki", "Let’s gooo!"),
        ("'Boom Boom Pow' - Black Eyed Peas", "Epic energy."),
        ("'Viva La Vida' - Coldplay", "Live loud, dream big."),
    ],
}


def get_suggestion(mood):
    return random.choice(mood_suggestions.get(mood, [("🎵 Music is healing", "You got this! ❤️")]))
